# Imagen base oficial de Python
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY . /app

# Instalar dependencias
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

# Exponer el puerto que usará Gunicorn
EXPOSE 8000

# Comando para iniciar la app con Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app:app"]