# Imagen base oficial de Python
FROM python:3.13-slim

# Establecer directorio de trabajo
WORKDIR /app

COPY requirements.txt .

# Instalar dependencias
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copiar archivos del proyecto
COPY . .

# Exponer el puerto que usará Gunicorn
EXPOSE 5000

# Comando para iniciar la app con Gunicorn
CMD ["gunicorn", "--workers", "4" ,"--bind", "0.0.0.0:5000", "app:app"]