"""modified column name  in table votacion, column raffle_price to precio_rifa

Revision ID: 54f59295cc06
Revises: f81379bd1cf6
Create Date: 2026-01-31 13:24:15.537901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54f59295cc06'
down_revision = 'f81379bd1cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rifa', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('raffle'))
        batch_op.create_unique_constraint(None, ['rifa'])
        batch_op.drop_column('raffle')

    with op.batch_alter_table('votacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_rifa', sa.Float(), nullable=False))
        batch_op.drop_column('raffle_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raffle_price', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('precio_rifa')

    with op.batch_alter_table('raffle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raffle', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('raffle'), ['raffle'], unique=True)
        batch_op.drop_column('rifa')

    # ### end Alembic commands ###
