"""delete unique in table raffle, column email

Revision ID: 87b1bc7177e5
Revises: 54f59295cc06
Create Date: 2026-02-01 14:17:21.722928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b1bc7177e5'
down_revision = '54f59295cc06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raffle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
