"""delete unique in table votacion, column raffle_price

Revision ID: f81379bd1cf6
Revises: d2f2f81ae56e
Create Date: 2026-01-31 13:19:11.539449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81379bd1cf6'
down_revision = 'd2f2f81ae56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('raffle_price'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('raffle_price'), ['raffle_price'], unique=True)

    # ### end Alembic commands ###
